# Generated by Django 4.1.3 on 2022-11-23 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('level_1', models.CharField(max_length=150, verbose_name='Уровень 1')),
                ('level_2', models.CharField(blank=True, max_length=150, verbose_name='Уровень 2')),
                ('level_3', models.CharField(blank=True, max_length=150, verbose_name='Уровень 3')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('price_sp', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='ЦенаСП')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('property', models.TextField(verbose_name='Поля свойств')),
                ('joint_purchases', models.CharField(max_length=150, verbose_name='Совместный покупки')),
                ('measure', models.CharField(max_length=50, verbose_name='Единицы измерения')),
                ('image', models.CharField(max_length=150, verbose_name='Картинка')),
                ('show_on_main', models.BooleanField(verbose_name='Выводить на главной')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'], message='Только .csv файлы')])),
                ('file_path', models.FilePathField(max_length=200)),
                ('time_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
