# Generated by Django 4.1.3 on 2022-11-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='joint_purchases',
            field=models.CharField(max_length=150, verbose_name='Совместные покупки'),
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='level_1',
            field=models.CharField(max_length=150, verbose_name='Уровень1'),
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='level_2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Уровень2'),
        ),
        migrations.AlterField(
            model_name='constructionmaterial',
            name='level_3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Уровень3'),
        ),
    ]
